import type { Article } from '@/types/article.type';

export const ARTICLES: Article[] = [
  {
    id: 1,
    title: 'Bí quyết kiếm 200k mỗi ngày chỉ bằng điện thoại',
    description: 'Phương pháp mà 10.000+ người đã áp dụng thành công, không cần vốn, chỉ cần 30 phút mỗi ngày.',
    category: 'HOT',
    gradient: 'from-orange-400 to-rose-500',
    emoji: '💰',
    timeLabel: '30 phút',
  },
  {
    id: 2,
    title: 'Flash Sale hôm nay: Giảm đến 80% — Chỉ còn 2 tiếng',
    description: 'Hàng trăm sản phẩm hot đang được sale sốc. Đừng để trễ rồi hối hận!',
    category: 'DEAL',
    gradient: 'from-red-500 to-orange-600',
    emoji: '🔥',
    timeLabel: 'Còn 2 tiếng',
  },
  {
    id: 3,
    title: 'Cách hoàn tiền 15% mỗi đơn hàng mà ít người biết',
    description: 'Trick đơn giản giúp bạn tiết kiệm hàng triệu đồng mỗi tháng khi mua sắm online.',
    category: 'MẸO',
    gradient: 'from-yellow-400 to-amber-500',
    emoji: '💡',
    timeLabel: '5 phút đọc',
  },
  {
    id: 4,
    title: 'Voucher ẩn Shopee lên đến 200k — Giới hạn 500 lượt',
    description: 'Mã giảm giá không được quảng cáo rộng rãi. Chỉ những người biết cách mới săn được.',
    category: 'DEAL',
    gradient: 'from-purple-500 to-pink-500',
    emoji: '🎁',
    timeLabel: 'Còn 500 lượt',
  },
  {
    id: 5,
    title: 'Sản phẩm trend TikTok bán chạy nhất tuần này',
    description: 'Những sản phẩm viral đang cháy hàng. Đặt trước ngay để không bỏ lỡ.',
    category: 'NHANH',
    gradient: 'from-blue-400 to-indigo-500',
    emoji: '⚡',
    timeLabel: 'Cập nhật hôm nay',
  },
  {
    id: 6,
    title: 'Mua điện thoại rẻ hơn 30% so với cửa hàng — Hướng dẫn chi tiết',
    description: 'Bí quyết mua công nghệ chính hãng với giá tốt nhất thị trường mà không sợ hàng giả.',
    category: 'MẸO',
    gradient: 'from-slate-600 to-slate-800',
    emoji: '📱',
    timeLabel: '20 phút đọc',
  },
  {
    id: 7,
    title: 'Mẹo freeship mọi đơn kể cả không đủ điều kiện',
    description: 'Cách đặt đơn thông minh để luôn được freeship, tiết kiệm 30–50k mỗi lần mua.',
    category: 'MẸO',
    gradient: 'from-green-400 to-emerald-500',
    emoji: '🚚',
    timeLabel: '5 phút đọc',
  },
  {
    id: 8,
    title: 'Combo mua 1 tặng 1 đang hot nhất Shopee tháng này',
    description: 'Danh sách sản phẩm đang áp dụng combo cực hời, được cập nhật liên tục mỗi ngày.',
    category: 'HOT',
    gradient: 'from-pink-500 to-rose-500',
    emoji: '🛍️',
    timeLabel: 'Còn 1 ngày',
  },
  {
    id: 9,
    title: 'Tích Shopee Xu nhanh nhất — Đổi quà trị giá triệu đồng',
    description: 'Chiến lược tích xu thông minh để đổi được những phần quà giá trị nhất.',
    category: 'NHANH',
    gradient: 'from-violet-500 to-purple-600',
    emoji: '💎',
    timeLabel: '15 phút đọc',
  },
  {
    id: 10,
    title: 'Deal công nghệ giảm 70% — Còn đúng 24 giờ để mua',
    description: 'Laptop, tai nghe, smartwatch đang được xả kho với mức giá không tưởng.',
    category: 'DEAL',
    gradient: 'from-cyan-500 to-blue-600',
    emoji: '🎯',
    timeLabel: 'Còn 24 giờ',
  },
];
